name: easix
description: easix is a helper package that provide multiple handy function to use in your flutter project.
version: 1.0.2
homepage: https://github.com/Mustafa7Ibrahim/easix.git

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
